services:
  - type: web
    name: laravel-app
    runtime: docker
    env: php
    buildCommand: docker build -t laravel-app .
    startCommand: docker run --rm -p $PORT:$PORT -e PORT=$PORT laravel-app
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: 127.0.0.1
      - key: DB_PORT
        value: 5432
      - key: DB_USERNAME
        value: mydb2_tdih_user
      - key: DB_PASSWORD
        value: oL3GFD96pKBFhtO5DE6Zrf7zptw2gU9j
      - key: DB_DATABASE
        fromDatabase:
          name: mydb2_tdih
          property: database